#7 Pin Terraform versions
FightPandemics/infrastructure pull request #8
Opened 2020-08-15 19:29 UTC by mannykary

We need to pin the versions as the new version of Terraform v0.13 has breaking changes.

Pin to Terraform v0.12.29, AWS provider version 2.70.0, and Mongo DB Atlas provider version 0.6.3.

Resolves #7

2020-08-15 20:41 UTC, joshmorel requested changes

2020-08-15 20:41 UTC, joshmorel commented on infra/deploy.sh
> +  required_version = "~> 0.12"
```suggestion
  required_version = "~> 0.12.29"
```

I didn't get the appropriate error (running 0.13.0) without including the patch.

Everything else look good!

From the docs:

> ~>: Allows the specified version, plus newer versions that only increase the most specific segment of the
> specified version number. For example, ~> 0.9 is equivalent to >= 0.9, < 1.0, and ~> 0.8.4, is equivalent to >= 
> 0.8.4, < 0.9. This is usually called the pessimistic constraint operator.

2020-08-15 21:49 UTC, joshmorel approved these changes
Great! (tested w both 0.12.29 & 0.13.0)

2020-08-16 07:24 UTC, ahmedasmar approved these changes
Everything looks fine, Thanks Manny

2020-08-17 00:34 UTC, merged

2020-08-17 14:10 UTC, royki commented
I tested using both `Terraform(v0.12.29)` & `Terraform(v0.13.0)`. Looks good.